- hosts: all
  tasks:
    - name: Create app dir
      ansible.builtin.file:
        path: /usr/local/ecomm_reporter
        state: directory
        mode: '0755'

    - name: Download Backend Binary
      ansible.builtin.unarchive:
        src: https://github.com/ipcrm/pandoras-box/releases/latest/download/ecomm-reporter-backend-linux-amd64.tar.gz
        dest: /usr/local/ecomm_reporter
        remote_src: yes
        mode: 0777

    - name: Write Config file
      blockinfile:
        path: /etc/ecomm_reporter_backend.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0600
        block: |
          ECOMM_BUCKET={{ ecomm_reporter_bucket }}
          ECOMM_STATICREGION={{ ecomm_reporter_bucket_region }}
          ECOMM_OBJECTSTORAGEENDPOINT={{ ecomm_reporter_object_storage_endpoint }}

    - name: Write systemd config file
      blockinfile:
        path: /etc/systemd/system/ecomm_reporter_backend.service
        create: true
        state: present
        block: |
          [Unit]
          Description=eCommerce Reporter Frontend

          [Service]
          EnvironmentFile=/etc/ecomm_reporter_backend.conf
          PIDFile=/var/run/ecomm_reporter-backend.pid
          Restart=always
          KillSignal=SIGQUIT
          WorkingDirectory=/usr/local/ecomm_reporter
          ExecStart=/usr/local/ecomm_reporter/bin/ecomm-rpt-be

          [Install]
          WantedBy=multi-user.target

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: ecomm_reporter_backend.service
        enabled: yes
        state: started

- hosts: all
  become: yes
  vars:
    deploydb: "{{ deploy_reporter_database }}"
    mysql_root_password: "{{ ecomm_database_pass }}"
    mysql_databases:
      - name: "{{ ecomm_database_name }}"
    mysql_users:
      - name: "{{ ecomm_database_user }}"
        host: "%"
        password: "{{ ecomm_database_pass }}"
        priv: "orders.*:ALL"
  roles:
    - role: geerlingguy.mysql
      when: deploydb
  tasks:
    - name: Download Sample Data
      ansible.builtin.unarchive:
        src: https://github.com/ipcrm/pandoras-box/releases/download/v0.0.1/reporter.sql.dump.tgz
        dest: /var/tmp
        remote_src: yes
        mode: 0777
      when: deploydb
    - name: Import sample data
      mysql_db:
        state: import
        name: "{{ ecomm_database_name }}"
        target: /var/tmp/reporter.sql.dump
        login_user: "{{ ecomm_database_user }}"
        login_password: "{{ ecomm_database_pass }}"
      when: deploydb
