- hosts: all
  tasks:
    - name: Create app dir
      ansible.builtin.file:
        path: /usr/local/ecomm_reporter
        state: directory
        mode: '0755'

    - name: Download Frontend Binary
      ansible.builtin.unarchive:
        src: https://github.com/ipcrm/pandoras-box/releases/latest/download/ecomm-reporter-frontend-linux-amd64.tar.gz
        dest: /usr/local/ecomm_reporter
        remote_src: yes
        mode: 0777

    - name: Download Client App Frontend
      ansible.builtin.unarchive:
        src: https://github.com/ipcrm/pandoras-box/releases/latest/download/frontend-client.tgz
        dest: /usr/local/ecomm_reporter
        remote_src: yes
        mode: 0777

    - name: Write Config file
      blockinfile:
        path: /etc/ecomm_reporter_frontend.conf
        create: true
        state: present
        owner: root
        group: root
        mode: 0600
        block: |
          ECOMM_AUTHTOKEN={{ ecomm_auth_token }}
          ECOMM_APPBUILDPATH=/usr/local/ecomm_reporter/frontend
          ECOMM_REPORTERENDPOINT=http://{{ ecomm_reporter_endpoint }}:9999
          ECOMM_DATABASEHOST={{ ecomm_database_host }}
          ECOMM_DATABASEPORT={{ ecomm_database_port | default("3306") }}
          ECOMM_DATABASENAME={{ ecomm_database_name }}
          ECOMM_DATABASEUSER={{ ecomm_database_user }}
          ECOMM_DATABASEPASS={{ ecomm_database_pass }}

    - name: Write systemd config file
      blockinfile:
        path: /etc/systemd/system/ecomm_reporter_frontend.service
        create: true
        state: present
        block: |
          [Unit]
          Description=eCommerce Reporter Frontend

          [Service]
          EnvironmentFile=/etc/ecomm_reporter_frontend.conf
          PIDFile=/var/run/ecomm_reporter-frontend.pid
          Restart=always
          KillSignal=SIGQUIT
          WorkingDirectory=/usr/local/ecomm_reporter
          ExecStart=/usr/local/ecomm_reporter/bin/ecomm-rpt-fe

          [Install]
          WantedBy=multi-user.target

    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        name: ecomm_reporter_frontend.service
        enabled: yes
        state: started
